version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    env_file:
      - fileName
    ports:
      - "3306:3306"
    volumes:
      - restramvp-db:/var/lib/mysql
    networks:
      - restramvp-net

networks:
  restramvp-net:
    driver: bridge

volumes:
  restramvp-db:
